from nltk.corpus import stopwords

FILE_PATH = "C:\\Users\\DLakin\\Desktop\\Github"
# FILE_PATH = "C:\\Users\\DLaki\\OneDrive\\Desktop\\Github"

TWEET_COLUMNS = ["id", "combined_text", "language", "has_mention", "num_mentions", "has_hashtags", "num_hashtags",
                 "gender"]

TWITTER_ROOT_URL = "https://api.twitter.com"

TWITTER_CONSUMER_KEY = "3RZxLkkQFDMnN3epDPOcP61hP"
TWITTER_CONSUMER_SECRET = "cwfoe7umOC4tAIJE4VmirEjmQE2NPWlnfCr91jS0EQUiOB4cNk"

SPACY_LANGS = ["de", "el", "en", "es", "fr", "it", "lt", "nb", "nl", "pt"]

POS_MAP = {
    "ADJ": "num_adjectives",
    "ADV": "num_adverbs",
    "CONJ": "num_conjunctions",
    "NOUN": "num_nouns",
    "NUM": "num_numerals",
    "PART": "num_particles",
    "PRON": "num_pronouns",
    "PROPN": "num_proper_nouns",
    "PUNCT": "num_punctuation_mks",
    "VERB": "num_verbs"
}

CONTRACTIONS = [
    "ain't",
    "aren't",
    "can't",
    "can't've",
    "'cause",
    "could've",
    "couldn't",
    "couldn't've",
    "didn't",
    "doesn't",
    "don't",
    "hadn't",
    "hadn't've",
    "hasn't",
    "haven't",
    "he'd",
    "he'd've",
    "he'll",
    "he'll've",
    "he's",
    "how'd",
    "how'd'y",
    "how'll",
    "how's",
    "I'd",
    "I'd've",
    "I'll",
    "I'll've",
    "I'm",
    "I've",
    "i'd",
    "i'd've",
    "i'll",
    "i'll've",
    "i'm",
    "i've",
    "isn't",
    "it'd",
    "it'd've",
    "it'll",
    "it'll've",
    "it's"
    "let's",
    "ma'am",
    "mayn't",
    "might've",
    "mightn't",
    "mightn't've",
    "must've",
    "mustn't",
    "mustn't've",
    "needn't",
    "needn't've",
    "o'clock",
    "oughtn't",
    "oughtn't've",
    "shan't",
    "sha'n't",
    "shan't've",
    "she'd",
    "she'd've",
    "she'll",
    "she'll've",
    "she's",
    "should've",
    "shouldn't",
    "shouldn't've",
    "so've",
    "so's",
    "that'd",
    "that'd've",
    "that's",
    "there'd",
    "there'd've",
    "there's",
    "they'd",
    "they'd've",
    "they'll",
    "they'll've",
    "they're",
    "they've",
    "to've",
    "wasn't",
    "we'd",
    "we'd've",
    "we'll",
    "we'll've",
    "we're",
    "we've",
    "weren't",
    "what'll",
    "what'll've",
    "what're",
    "what's",
    "what've",
    "when's",
    "when've",
    "where'd",
    "where's",
    "where've",
    "who'll",
    "who'll've",
    "who's",
    "who've",
    "why's",
    "why've",
    "will've",
    "won't",
    "won't've",
    "would've",
    "wouldn't",
    "wouldn't've",
    "y'all",
    "y'all'd",
    "y'all'd've",
    "y'all're",
    "y'all've",
    "you'd",
    "you'd've",
    "you'll",
    "you'll've",
    "you're",
    "you've"
]

STOP_WORDS = list(set(stopwords.words("english")))
